language: python
sudo: false
cache: pip

branches:
  except:
      - /^[^/]+/.+$/

python:
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial

install:
  - travis_retry pip install --upgrade setuptools pip pytest pytest-cov codecov
  - pip install setuptools_scm
  - pip install -e 'git+https://github.com/marrow/webcore.git@develop#egg=WebCore-2.1.0'
  - pip install -e '.[development]'

script:
    python setup.py test

after_script:
    bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - 'irc.freenode.org#webcore'
    use_notice: true
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository_slug}:%{branch}@%{commit} %{message}"
      - "Duration: %{duration} - Details: %{build_url}"
